name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      # Set up Dart
      - uses: dart-lang/setup-dart@v1

      # Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Configure Firebase (Generate firebase_options.dart)
      # - name: Configure Firebase
      #   run: |
      #     flutterfire configure --project=${{ secrets.FIREBASE_PROJECT_ID }} --platforms=android,ios,web --out=lib/firebase_options.dart
      #   env:
      #     FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}

      # Run Flutter tests
      - name: Run tests
        run: flutter test
