name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      # Set up Dart
      - uses: dart-lang/setup-dart@v1

      # Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Run Flutter tests
      - name: Run tests
        run: flutter test
